version: "3.8"

services:
  retail-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retail_intelligence_api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped

